### ISSUE TITLE
Is nostr-commits bot looking at all of github or a subset?

### ISSUE THREAD

**Issue by gsovereignty** [gourcetools/nostr-commits#1]
Is nostr-commits bot looking at all of github or a subset?

I have the nostr topic set on the repos in [this](https://github.com/nostrocket) org but the bot that publishes as `npub1qqqqqhu...` isn't picking up commits, just wondering.

**Comment by gourcetools** [comment]
I do see your commits in the nostr-commits timeline.

![image](https://user-images.githubusercontent.com/120996278/230932847-328a128f-519b-4f2a-9dff-6ec13f987a6f.png)


The commit bot that is running this code at https://nostr.band/npub1qqqqqhu87ep5rssjejfadsnxcqaww5kqyesw0znd59py77c9c3cqfec28r is grabbing any repo that have "nostr" as a topic.

If you want to create your own bot, please follow thesese steps. (Edit the scripts with the hex privkey you want to use to publish)

## Getting Started <br>
To get started with Nostr-Commits: clone the repo.
```
git clone https://github.com/gourcetools/nostr-commits
cd nostr-commits
```
Install Ocotkit and fs:
```
npm i fs
npm i octokit
```
Open both files to edit them (example command for Sublime Text): <br>
```
subl ./check_commits.sh
subl ./check_commits.js
```
**In the shell script:** edit the variables (PRIVKEY, RELAYS, POW, DELAY)
**In the Python script**, read comments as they will guide you through the setup process. 

![image](https://user-images.githubusercontent.com/120996278/228252469-dcba5ee8-6052-4b51-a1ef-224c58a8220e.png)

<br>Once you have completed these steps, save the files and run check-commits.sh to start the bot.
```
./check-commits.sh
```

The bot should be running, you can look at the console for informations about wha't going on.

![image](https://user-images.githubusercontent.com/120996278/228253457-bf2c9d17-8b9c-4bc2-ae04-506e9c677042.png)

**Comment by gourcetools** [comment]
Steps have changed. Please read the new readme and open a new issue if needed. Contact me if needed. Telegram best.

**Comment by gsovereignty** [comment]
Ah cool, thanks!
